
// AUTO-GENERATED FILE — DO NOT EDIT - Run "bun run generate:ajax" to regenerate, need to commit this file
export type WpAjaxAction =
  | "kj-get-expedition-ajax"
  | "nopriv_kj-get-expedition-ajax"
  | "kj-tracking-ajax"
  | "nopriv_kj-tracking-ajax"
  | "kiriminaja_subdistrict_search"
  | "nopriv_kiriminaja_subdistrict_search"
  | "getDestinationArea"
  | "nopriv_getDestinationArea"
  | "kj_get_data_after_update_checkout"
  | "nopriv_kj_get_data_after_update_checkout"
  | "kj_request_pickup_schedule"
  | "kj_request_pickup_transaction"
  | "kj_transaction-detail-summary"
  | "kj_get_integration_data"
  | "nopriv_kj_get_integration_data"
  | "kj_store_integration_data"
  | "nopriv_kj_store_integration_data"
  | "kj_disconnect_integration"
  | "nopriv_kj_disconnect_integration"
  | "kj_get_origin_data"
  | "nopriv_kj_get_origin_data"
  | "kj_store_origin_data"
  | "nopriv_kj_store_origin_data"
  | "kj_get_call_back_data"
  | "nopriv_kj_get_call_back_data"
  | "kj_store_call_back_data"
  | "nopriv_kj_store_call_back_data"
  | "kiriminaja_search_expedition"
  | "kj_get_shipping_process_detail"
  | "kj_get_payment_form"
  | "kj_get_shipping_reschedule_pickup"
  | "kiriminaja_get_settings"
  | "kiriminaja_save_settings";
