/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigAdvanced: typeof import('./components/config/advanced.vue')['default']
    ConfigIntegration: typeof import('./components/config/integration.vue')['default']
    ConfigShipping: typeof import('./components/config/shipping.vue')['default']
    CoverageSearch: typeof import('./components/coverage/search.vue')['default']
    Page: typeof import('./components/page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAlert: typeof import('./components/ui/alert.vue')['default']
    UiButton: typeof import('./components/ui/button.vue')['default']
    UiCard: typeof import('./components/ui/card.vue')['default']
    UiCheckbox: typeof import('./components/ui/checkbox.vue')['default']
    UiCombobox: typeof import('./components/ui/combobox.vue')['default']
    UiForm: typeof import('./components/ui/form.vue')['default']
    UiFormField: typeof import('./components/ui/form-field.vue')['default']
    UiInput: typeof import('./components/ui/input/index.vue')['default']
    UiTable: typeof import('./components/ui/table.vue')['default']
    UiTextarea: typeof import('./components/ui/textarea.vue')['default']
    UiToast: typeof import('./components/ui/toast.vue')['default']
  }
}
