name: Plugin Wordrpress Kiriminaja Development
on:
  push:
    branches:
      - development

jobs:
  upload-gcs-prd:
    name: "Build & Push"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current time
        id: date
        run: echo "::set-output name=date::$(TZ="Asia/Jakarta" date +'%Y-%m-%d %H:%I')"

      - name: Archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: kiriminaja-${{ github.ref_name }}.zip
          exclusions: "*.git* *.github* /*node_modules/* .editorconfig .gitattributes /.gitignore .prettier* .stylelintrc* .vscode* /.wordpress-org/"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_PRD_CICD }}

      - name: Uploading ZIP
        id: upload-zip
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: kiriminaja-${{ github.ref_name }}.zip
          destination: ${{ secrets.GCS_KA_PRD_WEB }}/wp
          predefinedAcl: "publicRead"
          headers: |
            cache-control: no-store, no-cache, must-revalidate, max-age=0

#  deploy:
#    runs-on: [self-hosted,kaj-dev-runner]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Deploy
#        run: |
#          cd /home/devstag/kaj-dev-latest-plugin-wp/wp-content/plugins/plugin-wp # navigate into the folder
#          git pull origin development # pull the latest code from branch development
