name: Plugin Wordrpress Kiriminaja Staging
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: [self-hosted,kaj-dev-runner]
    steps:
      - uses: actions/checkout@v2
         
      - name: Deploy
        run: |
          cd /home/devstag/kaj-stg/kaj-stg-latest-plugin-wp/wp-content/plugins/plugin-wp # navigate into the folder
          git pull origin staging # pull the latest code from branch staging